name: Publish from Firebase Studio

on:
  workflow_dispatch: {}
  repository_dispatch:
    types: [firebase-studio-publish, firebase-studio-update]

permissions:
  contents: write
  pull-requests: write

env:
  TARGET_BRANCH: main
  FIREBASE_PROJECT_ID: ai-artifacts-journey
  FIREBASE_HOSTING_SITE: ai-artifacts-journey

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure git identity
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      # Rakenna appit jos niillä on oma package.json apps/* -hakemistoissa
      - name: Build apps (if package.json exists)
        run: |
          set -e
          for app in webappstory HSTPT cosmicweather photoadventure; do
            if [ -f "apps/$app/package.json" ]; then
              echo "Building apps/$app…"
              (cd "apps/$app" && npm ci && npm run build)
            else
              echo "Skipping apps/$app (no package.json)"
            fi
          done

      # (Valinnainen) leimataan julkaisuhetki että syntyy commit
      - name: Stamp publish info
        run: |
          mkdir -p tools
          echo "{\"publishedAt\":\"$(date -u +%Y-%m-%dT%H:%M:%SZ)\"}" > tools/firebase-studio-sync.json

      - name: Commit changes (if any)
        run: |
          git add -A
          if git diff --cached --quiet; then
            echo "No changes to commit."
          else
            git commit -m "chore: publish via Firebase Studio"
          fi

      - name: Push to default branch (token remote)
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git remote set-url origin https://x-access-token:$GITHUB_TOKEN@github.com/$GITHUB_REPOSITORY.git
          git push origin HEAD:$TARGET_BRANCH || true

      - name: Install Firebase CLI
        run: npm i -g firebase-tools

      # Vapaaehtoinen: listaa mitä ollaan deployaamassa
      - name: List files under apps/
        run: |
          ls -la apps || true
          find apps -maxdepth 2 -name index.html | sed 's/^/ • /' || true

      - name: Deploy to Firebase Hosting (default site)
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
        run: |
          firebase deploy --only "hosting:${FIREBASE_HOSTING_SITE}" --project "$FIREBASE_PROJECT_ID" --non-interactive
