name: Publish from Firebase Studio

on:
  workflow_dispatch: {}
  repository_dispatch:
    types: [firebase-studio-publish, firebase-studio-update]

permissions:
  contents: write
  pull-requests: write

env:
  TARGET_BRANCH: main
  FIREBASE_PROJECT_ID: ai-artifacts-journey
  FIREBASE_HOSTING_SITE: ai-artifacts-journey
  # Lista applikaatiokansioista firebase.jsonin rewriten mukaan (apps/<APP>/dist/index.html)
  APP_DIRS: "webappstory HSTPT cosmicweather photoadventure"

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure git identity
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

      # Luo placeholderit vain jos dist/index.html puuttuu
      - name: Ensure dist placeholders (only if missing)
        run: |
          set -e
          mkdir -p apps
          for app in $APP_DIRS; do
            mkdir -p "apps/$app/dist"
            f="apps/$app/dist/index.html"
            if [ ! -f "$f" ]; then
              echo "<!doctype html><html><head><meta charset='utf-8'><title>$app</title></head><body><h1>$app placeholder</h1><p>Generated at $(date -u +%Y-%m-%dT%H:%M:%SZ)</p></body></html>" > "$f"
              echo "Created $f"
            else
              echo "Exists: $f"
            fi
          done

      # (Valinnainen) pieni leima, jotta commit varmasti syntyy
      - name: Stamp publish info
        run: |
          mkdir -p tools
          echo "{\"publishedAt\":\"$(date -u +%Y-%m-%dT%H:%M:%SZ)\"}" > tools/firebase-studio-sync.json

      - name: Commit changes (if any)
        run: |
          git add -A
          if git diff --cached --quiet; then
            echo "No changes to commit."
          else
            git commit -m "chore: publish via Firebase Studio (placeholders)"
          fi

      - name: Push to default branch (token remote)
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git remote set-url origin https://x-access-token:$GITHUB_TOKEN@github.com/$GITHUB_REPOSITORY.git
          git push origin HEAD:$TARGET_BRANCH || true

      - name: Setup Node (for Firebase CLI)
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Firebase CLI
        run: npm i -g firebase-tools

      # Pieni diagnostiikka: näkyykö dist/index.html -tiedostoja?
      - name: List dist index files
        run: |
          echo "Looking for apps/*/dist/index.html ..."
          find apps -type f -path "*/dist/index.html" -print | sed 's/^/ • /' || true

      - name: Inspect Hosting setup (sites & domains)
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
        run: |
          firebase hosting:sites:list --project "$FIREBASE_PROJECT_ID"
          echo "-----"
          firebase hosting:domains:list --project "$FIREBASE_PROJECT_ID" || true

      - name: Deploy to Firebase Hosting
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
        run: |
          firebase deploy --only "hosting:${FIREBASE_HOSTING_SITE}" --project "$FIREBASE_PROJECT_ID" --non-interactive
